---
applications:
  - name: carbon-storybook-vue
    memory: 64M
    buildpack: https://github.com/cloudfoundry/staticfile-buildpack.git
    routes:
      - route: vue.carbondesignsystem.com
      - route: carbon-vue-storybook.mybluemix.net
