name: Release

on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies from our offline mirror
        run: yarn install --offline

      - name: Build project
        run: yarn build

      - name: Run Continuous Integration checks
        run: yarn ci-check

      # Dry run - `yarn lerna version --no-git-tag-version --no-push --yes`
      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_LERNA }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: lerna publish --create-release github --yes --dist-tag canary
