name: Release

on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v*-test'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies from our offline mirror
        run: yarn install --offline

      - name: Build project
        run: yarn build

      - name: Run Continuous Integration checks
        run: yarn ci-check

      - name: Publish packages under the `next` dist tag
        run: yarn lerna publish from-package --dist-tag next --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
